### ISSUE TITLE
Dúvida sobre o Render do projeto

### ISSUE THREAD

**Issue by thiagommedeiros** [pagarme/artis#104]
Questão levantada pelo @vcapretz no Slack:

> só que o ponto é: um app react de verdade tem um public/index.html, que contém um div pai, ou mesmo só o body, o webpack processa isso e adiciona o js gerado nos scripts, dentro do header, pra fazer a parada funcionar.
> 
> o src/index.js tem o render master do react, que pega o componente paizão e renderiza na div root (ou dentro do body). 
> 
> a questão aqui é: nós nao sabemos onde renderizar até o cliente dizer em qual elemento o checkout vai abrir. uma possível solução é tirarmos a opcao do cliente de escolher onde renderizar, e deixar com o nosso app a responsabilidade de criar uma div com uma classe/id aleatorio pra nao dar conflito com o html dele e renderizarmos lá.
> 
> 
> outra questão que fico pensando: o JS final gerado pelo webpack na build nao faz com o que o React seja dependencia né? pode ser colocado em qualquer pagina que funciona?

**Comment by allangrds** [comment]
Sobre essa parada do Webpack, até onde sei, você precisa configurá-lo se quiser separar o código que vocês está desenvolvendo dos vendors, então eu diria que sim, o código que geramos já possui as dependências.

**Comment by mccraveiro** [comment]
Eu gosto da opção do checkout criar uma div no body e renderizar lá dentro. Eu só tomaria cuidado com conflitos de `z-index`.

**Comment by vcapretz** [comment]
é assim que estamos seguindo até quando der @mccraveiro!
