### ISSUE TITLE
Color names

### ISSUE THREAD

**Issue by augusto-jm-amaral** [pagarme/artis#105]
We need to standardize the names of the colors we declare.

Suggestion: Use the brightness to set the color tone.

```css
--color--{tonality}--{brightness in %}
```

We can use the [workwithcolor](http://www.workwithcolor.com/color-converter-01.htm)

**Comment by vcapretz** [comment]
does https://github.com/pagarme/artis/pull/145 solves this @augusto-jm-amaral?

**Comment by vcapretz** [comment]
já está feito!
