### ISSUE TITLE
Mover pastas e arquivos do Redux

### ISSUE THREAD

**Issue by allangrds** [pagarme/artis#178]
## Description
Minha ideia era colocar a pasta `reducers`, `actions` e a store dentro de uma pasta `redux` ou `flux`, pra centralizar todos eles em um lugar.

**Comment by vcapretz** [comment]
não sei se é válido, as pastas estão organizadas de acordo com os padrões utilizados em vários outros projetos, isso faz com que qualquer pessoa saiba onde procurar cada coisa.

**Comment by allangrds** [comment]
Bom, acho que do modo que sugeri também não seria difícil. Sabendo ler, consegue. Afinal, o nome da pasta pai teria algo relacionado a flux/redux/whatever.
