### ISSUE TITLE
Temos um problema de CSS para resolver!

### ISSUE THREAD

**Issue by thiagommedeiros** [pagarme/artis#26]
Conversando com algumas pessoas da Pagar.me, inclusive com aval do time de Segurança, optamos por não fazer o checkout dentro de um `iframe`. Porém, nos deparamos com um problema e não sabemos exatamente como resolver, então vamos discutir nessa issue soluções para isso.

## O problema

Basicamente o checkout será montado dentro uma `div` especificada pelo cliente:

``` html
<html>
  <body>
    <!-- o cliente escolheu essa div para montar o checkout -->
    <div id="wrapper-checkout">
      <!-- o checkout cria uma outra div aqui dentro -->
      <div class="checkout">
        ...
      </div>
    </div> 
  </body>
</html>
```

O checkout terá seus próprios styles a partir da div com a classe `.checkout`. Porém,  o cliente pode definir algum style do seu site com `!important`, e isso pode sobrescrever os styles do checkout, exemplo:

``` css
/* style do cliente */
h1 { font-size: 50px !important; }

/* style do checkout */
.checkout h1 { font-size: 30px; }
```

Como podemos resolver isso?

**Comment by vcapretz** [comment]
Não gosto da ideia de adicionarmos important, continua sendo uma prática ruim e do mesmo jeito que o css do cliente pode causar comportamentos inesperados no nosso, o contrário também pode acontecer! 

Estamos descartando mesmo a opção de fazer via iframe? 

@derekstavis @felquis @MarcoWorms, se quiserem nos ajudar aqui

**Comment by allangrds** [comment]
Como o @vcapretz disse, usar `!important` é bem ruim. Uma alternativa é mudarmos o modo como criamos os estilos do checkout.

Eu cheguei a comentar com vocês uma vez, de usar algum css style guide. Curto e tento usa o [`RSCSS`](http://rscss.io/index.html) pq ele consegue deixar as coisas verbosas, e bem definidas. Vamos por um momento esquecer o problema do style na parte do cliente, e vamos nos concentrar em `.checkout h1`. Se eu mudar no html o h1 para h2 o estilo vai quebrar, e precisarei mudar o css também. Um modo super recomendado de fazer isso, é utilizar classes para estilização, e parar de usar tags como referência. Usando uma classe, não teríamos mais o problema com o `!important` no cliente, pois a especificação na classe tem uma prioridade maior que a atribuição via child element.

Segue abaixo um teste feito usando `.classePai > tagFilho`:
https://codepen.io/anon/pen/xpEbvz?editors=1100

Desse modo, como o @thiagommedeiros disse, o estilo do cliente iria se sobrepor.

Mas agora, vamos utilizar um método usando classes:
https://codepen.io/anon/pen/zpKxgR?editors=1100

Viu só? Mesmo com o `!important`, a classe teve prioridade para definir o estilo do elemento.

Acho que usando um sistema de classes a gente só tem benefícios:
- Estilo não entra em conflito com o do cliente;
- Performance é afetada positivamente ligeiramente;
- Facilita a manutenção, já que o element no HTML só precisa ter a classe.

*Links para referência*
http://rscss.io/elements.html
https://www.felipefialho.com/blog/2016/porque-usar-classes-para-estilizar-elementos

**Comment by allangrds** [comment]
> Encontrei um plugin simples para webpack que adiciona !important em todos styles do projeto, ou seja, podemos escrever o css normalmente e o bundle final terá os !important para sobreescrever qualquer css do site que esteja alterando os styles do checkout.

Temos que tomar muito cuidado com isso @thiagommedeiros, pq o tiro pode acabar saindo pela culatra pelo uso de `!important` no código inteiro. Mas pra manter a UI intacta pro cliente, caso ele realmente faça isso, não vejo outra maneira.

**Comment by thiagommedeiros** [comment]
@allangrds @vcapretz Concordo com vcs, eu também sou adepto de boas práticas, mas algumas vezes (se não tivermos alternativas) precisamos abrir mão delas em prol da experiência do usuário e da satisfação do nosso cliente.

Essa ideia de usar `important` na hora de buildar o projeto é apenas um start pra a gente estressar esse assunto até a gente encontrar uma solução ideal, então, fiquem a vontade para sugerir qualquer ideia maluca.

**Comment by augusto-jm-amaral** [comment]
Pensei em uma possível solução, podemos definir `hashs` nos nomes das classes no script do webpack de produção, dessa forma as classes seriam únicas na página, e na raiz do checkout utilizar um id `id=hash` assim `#hash` também e a partir dele podemos fazer um reset nos elementos. Como o `id` tem maior prioridade não teria como algo afetar o escopo dele. Isso vai evitar qualquer conflito com as classes existentes na página do cliente. Da para testar isso.

**Comment by marquinhoalm** [comment]
Uma idéia meio besta, mas se utilizar um prefixo "padrão" já ajudaria bastante não? ex: `id=artis-card-brand`. Ignorem se falei 💩  😂

**Comment by augusto-jm-amaral** [comment]
@marquinhoalm que isso precisamos de ideias

**Comment by vcapretz** [comment]
usar id não funciona, important ainda sobrescreve, e por usarmos css-modules já não temos problemas com nomes de classe, se o cliente tiver uma classe `checkout` ela não interfere na nossa, que é processada e vira um nome diferente. 

uma solução que vi agora é https://developer.mozilla.org/en-US/docs/Web/Web_Components/Shadow_DOM mas ainda tem razoavelmente pouco suporte, podemos alertar em browsers mais antigos que se o usuário tiver !important no css isso pode atrapalhar o estilo do modal (em React tem um pacote já pra isso https://github.com/Wildhoney/ReactShadow)

outra solução que resolve sem problema é iframe, sei que o @thiagommedeiros tem algumas considerações, mas podemos renderizar em iframe e tentar ver as merdas que pode dar (ver no mobile se continua bom etc)

**Comment by thiagommedeiros** [comment]
@vcapretz Sugiro então a gente validar a ideia de usar iframe. A gente cria uma Task na próxima sprint justamente para isso, assim podemos validar questões como: performance (principalmente em mobile), responsividade, ux, transmissão de dados, etc. Com isso conseguimos levantar todos os pontos positivos e negativos pra tomar uma decisão.

**Comment by augusto-jm-amaral** [comment]
Uma outra possível solução seria utilizar um `loader`  que adiciona `!important` que o @thiagommedeiros sugeriu e  também um `loader` que transforma o `css` em inline style, quanto ao último encontrei alguns semelhantes mais nada no que a gente realmente precisa.

Seria assim:

```css
/* index.css */
.button {
  color: #545454;
}
```

```jsx
import React from 'react'
import style from './index.css'

console.log(style) // -> { button: ´color: #545454 !important;´ }

Button = () => <button Style={style.button}></button>

```

Usando a `prop` `Style` que serve para adicionarmos `css` inline a um componente, assim garantimos que nosso `css` não vai ter um comportamento inesperado na página que implementa o _Artis_ e vice-versa. 

Caso não conseguirmos fazer isso com um loader existentes, podemos desenvolver um com base em alguns já no mercado. Olhando alguns talvez não seja algo tão complicado de ser desenvolvido.

**Comment by vcapretz** [comment]
usar o !important por mim deve ser descartado, já que não é uma prática css adequada. 
quanto ao css-inline não tenho certeza, devemos lembrar que em breve teremos a estratégia de temas a ser implementada, esses temas poderão ser carregados e alterados de fora

podemos incluir nas tarefas dos próximos dias uma para testarmos o uso de iframe

**Comment by augusto-jm-amaral** [comment]
Quanto ao `!important` ele só vai ser adicionado ao traspilar o arquivo `css`, Já o `react-css-themr` ele é apenas uma forma de disponibilizar o style entre a arvore de componentes, os `loaders` vão continuar como estão, ele adiciona o todo o style no [context](https://reactjs.org/docs/context.html) da aplicação e utilizando `HOC` que acessa o _context_ e injeta as classes nos respectivos componentes.

Concordo com a abordagem, vamos testar o _iframe_ primeiro.

**Comment by marquinhoalm** [comment]
Deveriamos mesmo fazer algo como *iframe* por causa disso? Se tivermos um manual bem explicado de como funciona os nosso estilos não deveria resolver isso? Vamos arriscar perder performance ou qualidade por uma implementação incorreta de css? Só jogando perguntas no ar mesmo =)

**Comment by thiagommedeiros** [comment]
Eu concordo com o @marquinhoalm sobre iframe. 

Sobre usar `important` eu concordo que é uma má prática, mas isso apenas no ambiente de desenvolvimento, estamos falando de colocar `important` no bundle final para garantir que nada sobreescreva os styles do checkout, isso nao vai afetar nada o ambiente de desenvolvimento. Talvez seja 'semelhante' usar polyfills ou transpilers para javascript, onde o bundle final fica com um código longe de usar boas práticas.

**Comment by thiagommedeiros** [comment]
O `important` resolve apenas uma parte do problema, imagine que o cliente por algum motivo tenha isso:

``` css
h2 {
   display: block;
   width: 50px;
   height: 50px;
}
```

Ou seja, isso vai fazer todos os `h2` do checkout ter `width` e `height`. Teríamos que resetar com important todas as propriedades de css de cada seletor, acho que é inviável. Meu ponto é que não temos como ter controle de tudo e resolver todos esses problemas, apenas com iframe. 

Se a gente não usar iframe precisamos pelo menos garantir o básico (minha sugestão é o `important`) e ter uma documentação bem clara sobre isso pra se o checkout do cliente ficar bizarro ele conseguir identificar rapidamente qual é o problema.

**Comment by marquinhoalm** [comment]
Não vejo muito milagre pro css, ou você mete o `!important` ou designer do cliente vai ter que cuida do css.

Mas TODAS as nossas classe tem que tem algo extremamente específico nosso para usar o `!important`.

Mas como o @thiagommedeiros falou não deve existir isso no código de desenvolvimento.

Isso não deveria existe (não sei se tem atualmente)
``` css
h2 {
   display: block;
   width: 50px;
   height: 50px;
}
```
Deveria sempre ser específico
``` css
.artis-checkout h2 {
   display: block;
   width: 50px;
   height: 50px;
}
```

**Comment by thiagommedeiros** [comment]
Criei esse codepen pra ficar mais facil de entender/testar o problema: https://codepen.io/pagarme/pen/MrpwbK

**Comment by vcapretz** [comment]
então, por mim podemos deixar claro essa questão de que o css pode impactar, com classes não vai dar problema de conflito porque usamos css-modules, e como usamos essa regra de style guide: https://github.com/pagarme/react-style-guide#never-use-id-and-tag-name-as-root-selectors não vamos perder na prioridade se o cliente tiver um h1 mudando tudo.

então teoricamente não está tão ruim, deixaria assim e não colocaria important nem no bundle final, já que ele vai ser importado no cliente e também não queremos que o contrário aconteça (nosso css afetando o dele de alguma forma)

**Comment by thiagommedeiros** [comment]
@vcapretz abre o codepen que eu coloquei aqui e faz uns testes. Mesmo colocando classes o problema continua. Acredito que está ruim sim pq é bem comum sites estilizarem algumas tags diretamente como `h1, h2, p, label, a`, entre outras. Se isso acontecer com nosso cliente oq vamos dizer pra ele? "Altere todo seu css"?

**Comment by marquinhoalm** [comment]
@thiagommedeiros @vcapretz achei uma maneira de reset o `css` de uma component.

Em cada item teria que ter um `all: unset`. Coloquei o exemplo que o @thiagommedeiros deu com essa prop.

https://codepen.io/anon/pen/BJWNEa

**Comment by marquinhoalm** [comment]
https://developer.mozilla.org/pt-BR/docs/Web/CSS/unset

**Comment by marquinhoalm** [comment]
O `all` vai resetar tudo, mas da pra aplicar também em uma específica se precisar.

**Comment by vcapretz** [comment]
uma solução que não vimos ainda é o Shadow DOM https://developer.mozilla.org/en-US/docs/Web/Web_Components/Shadow_DOM 

o único problema vai ser compatibilidade, ta implementado em poucos browsers isso

**Comment by augusto-jm-amaral** [comment]
Galera montei um **codepen** pra entrar na brincadeira rs. 

https://codepen.io/augustojmamaral/pen/ppeJqE

Tem style `!important` antes e depois do component, o style do componente não vai repercutir nos demais da página, acho que não ficou claro o que eu tinha falado acima, dessa forma fica mais claro.

lembrando que o `Style` com s maiúsculo só é suportado pelo React 16+.

Mesmo com essa abordagem o `reset` é necessário.

**Comment by derekstavis** [comment]
Eu iria de `iframe`. É como a indústria tem resolvido o problema de vazamento de escopo (tanto de CSS quando de JS). É só conferir como a maior parte das integrações (facebook, hotjar, etc) funcionam. Além de resolver esse problema específico Isso também vai dar mais segurança pra implementação do checkout, pois vamos estar em um iframe dentro do domínio do pagar.me.

**Comment by lucasjs** [comment]
@marquinhoalm o `all ` é lindo, mas o grande problema é o suporte para ie/edge.

[https://caniuse.com/#feat=css-all](https://caniuse.com/#feat=css-all)

**Comment by marquinhoalm** [comment]
Kill the IE @lucasjs 😂

**Comment by vcapretz** [comment]
queria muito @marquinhoalm hahahha a partir do Google Analytics vimos que os browsers mais relevantes que usam o Checkout atual incluem IE à partir do 10, vamos ter que dar suporte pelo menos para essas últimas versões 😔

**Comment by Deivis** [comment]
Bem interessante o ponto do Style @augusto-jm-amaral, se vocês já usam o reac 16 vale a pena estudar isso.
Este caso de prioridade do css é bem tenso, por mim um bom disclaimer bom no readme do componente e classes especificas ( evitar seletores compostos por tags ) seriam suficiente para o cliente entender como usar e o que pode afetar o checkout.

**Comment by Deivis** [comment]
Caramba demorei tanto pra escrever que já voltamos ao iFrame @derekstavis  🙃 
Mas como mencionastes é a solução mais robusta par o problema

**Comment by thiagommedeiros** [comment]
Sobre a sugestão do @marquinhoalm de usar o `all: initial;` tem um plugin de postcss que faz um hack disso: https://github.com/maximkoretskiy/postcss-initial.
