### ISSUE TITLE
BrowserStack - Testes em Browsers e S.O's

### ISSUE THREAD

**Issue by thiagommedeiros** [pagarme/artis#43]
Precisamos desenvolver um `bot` que utiliza o serviço do **BrowserStack** para automatizar nossos testes e gerar prints de navegação das páginas do Checkout em diversos browsers e sistemas operacionais diferentes. Esses prints deverão ser analisados pela equipe do Checkout com objetivo de encontrar problemas críticos no layout.

Para isso, eu fiz um levantamento pelo Google Analytics dos Browsers e S.O's mais utilizados no Checkout da Pagar.me no período de 1 ano: entre 07/12/2016 à 07/12/2017.

Abaixo, segue os dados coletados que deverão nortear o desenvolvimento do `bot`:

## Browsers
Em ordem, os mais utilizados e a versão mínima que devemos oferecer suporte:
- Chrome - 55.0
- Firefox - 38.0
- Android - 30.0
- Edge - 12.1
- Safari - 9.0
- Internet Explorer - 11.0
- Opera - 42.0

## S.O's
Em ordem, os mais utilizados e a versão mínima que devemos oferecer suporte:
- Windows - 7
- Android - 5.1.1
- Mac OS X - 10.12 (Sierra)
- iOS - 10.2.1

**Comment by augusto-jm-amaral** [comment]
Para esta atividade, optamos por escrever uma lib, está sendo implementada no repositório [browserstack-automated](https://github.com/pagarme/browserstack-automated).

- [X] Implementar logica de concorrência de tests
- [X] Adicionar Lint
- [ ] Refactor
- [ ] Adicionar Babel
- [ ] Adicionar Testes de unitários
- [ ] Executar Binário automaticamente (teste local)
- [ ] Update README
- [ ] Publicar
