### ISSUE TITLE
Criar parâmetro "customerData"

### ISSUE THREAD

**Issue by vcapretz** [pagarme/artis#58]
No checkout 1.0 e 1.1 uma das propriedades que o cliente passa é `data-customer-data`, que habilita os passos necessários para que sejam incluídas informações sobre o comprador e serão posteriormente enviadas para o antifraude. 

Isso é algo que pensamos nesse checkout? Se sim, talvez seja necessário criar uma task para que possamos inserir no App alguma prop que valide se deve ou não mostrar os primeiros passos

Ref.: https://github.com/pagarme/mercurio/issues/5

**Comment by thiagommedeiros** [comment]
@vcapretz Esse comportamento deve existir nesse checkout também, o cliente deve ter as duas opções: 

1. Formulário de `customer` habilitado (default), o usuário preenche os dados.
1. Formulário de `customer` desabilitado, o lojista nos envia os dados pela integração.

Atualmente o parâmetro é booleano e se chama `customerData`, eu não acho esse nome ruim, mas se alguém tiver uma sugestão melhor podemos discutir.

Vou colocar essa Issue como `to do` e adiciona-la no nosso backlog.

**Comment by thiagommedeiros** [comment]
Uma ideia: dado que a função desse parâmetro é exibir ou não o formulário de customer eu sugiro alterar o nome para `customerForm`.

**Comment by vcapretz** [comment]
seguiremos com a estratégia de que se o lojista passar o parâmetro não iremos pedir novamente
