### ISSUE TITLE
Telas MVP Checkout

### ISSUE THREAD

**Issue by IedaOtero** [pagarme/artis#61]
**O que é o MPV de Checkout?**
Corresponde ao processo de finalização de uma compra usando cartão de crédito ou boleto bancário. Faremos de forma responsiva, então precisaremos das **telas desktop e mobile**, mantendo consistência entre eles.

**Telas MVP** 

**Tema:** Dark

**Cor default:** Situação/cor default caso o lojista não escolha a cor primária do checkout.

**Erros:** exemplo campos com dados inconsistentes.

**Textos:** atualizar com textos finais revisados pela Bia

**Passos:**

1. Identificação do cliente
- [x] Dados pessoais (Nome, E-mail, CPF, DDD e telefone);

2. Endereço de cobrança
- [x] CEP, Rua, número, complemento, bairro, cidade, estado;

3. Endereço de entrega
- [x] mesmo endereço de cobrança e outro endereço já cadastrado;
- [x] fluxo de excluir endereço cadastrado;
- [x] fluxo de editar endereço cadastrado;
- [x] fluxo de cadastrar novo endereço de entrega.

4. Forma de pagamento 

_Cartão de crédito:_ 
- [x] Imagem do cartão sem dados preenchidos (ficará vazio)?
- [x] Imagem do cartão com dados preenchidos
- [ ] Verso do cartão sem dados preenchidos (ficará vazio)?
- [ ] Verso do cartão com dados preenchidos 
- [x] Valor da compra, 
- [x] Número do cartão
- [x] Nome
- [x] Quantidade de parcelas (simular o comportamento)
- [x] Data de validade
- [x] Cvv (simular tooltip)

_Boleto bancário_
- [ ] É necessário ter uma confirmação/ clique para gerar o boleto (manter consistência do fluxo de confirmação da tela de cartão de crédito)

5. Mensagem feedback da transação
- [x] Mensagem de sucesso de Cartão de crédito

_Mensagem de sucesso de Boleto_ 
Inserir as funcionalidades de:
- [x] Salvar arquivo 
- [x] Encaminhar por email (comportamento)
- [x] Copiar código de barras (comportamento)
- [ ] Mensagem aguardando confirmação

6. Mensagem de transação recusada
Referência de textos e situações de erro: pagarme-checkout #142
- [x] Mensagem de recusa de Cartão de crédito
- [ ] Mensagem de recusa de Boleto

**Comment by IedaOtero** [comment]
@alexandralugli conforme combinamos, segue lista com o que precisamos em detalhe para o MVP do checkout. Consegue me dar uma previsão de data?

**Comment by alexandralugli** [comment]
@IedaOtero Estou focada no checkout para entregar todos esses ajustes e cenários que faltam do mvp e styleguide. Subo no Zeplin até o dia 12/01.

**Comment by allangrds** [comment]
Checkout já está em alfa. Encerrando issue.
