### ISSUE TITLE
Tela de confirmação

### ISSUE THREAD

**Issue by thiagommedeiros** [pagarme/artis#74]

**Comment by vcapretz** [comment]
@alexandralugli os icones dessa tela de sucesso serão desenvolvidos por vcs? segundo o modelo atual temos um icone de sucesso e um de erro, nas opções dark e light https://app.zeplin.io/project/59e66a2ad508e5fb822f1776/screen/59e75a8daa565b58180d071b

**Comment by thiagommedeiros** [comment]
Transferido para: https://github.com/pagarme/mercurio/issues/20
