### ISSUE TITLE
Criar validação de inputs

### ISSUE THREAD

**Issue by thiagommedeiros** [pagarme/artis#76]

**Comment by allangrds** [comment]
Essa validação será feita somente no submit do formulário ou ao trocar de input?

**Comment by thiagommedeiros** [comment]
@allangrds Acredito que validar ao trocar de input seja o comportamento mais adequado. Mas quem pode responder isso melhor talvez seja a própria @IedaOtero e/ou a galera de UI/UX.

**Comment by vcapretz** [comment]
@allangrds em ambos! A cada input que troco ele vai validar, mas imagina que o CEP preenche um monte de campo em automático com abobrinha, na hora que eu clicar em submit todos os inputs ue tiverem erro deverão ficar com a cor vermelha

**Comment by allangrds** [comment]
Deixando tarefa on-hold. Aguardando Vitor ou Derek disponibilizarem uma lib bacanuda.

**Comment by augusto-jm-amaral** [comment]
Transferindo para https://github.com/pagarme/mercurio/issues/25.
