### ISSUE TITLE
Corrigir styles do componente Button

### ISSUE THREAD

**Issue by thiagommedeiros** [pagarme/artis#78]

**Comment by vcapretz** [comment]
tem como fazer isso no PR que irei abrir passando os estilos atuais pro modelo de temas, por si só muita coisa já foi alterada na estrutura

**Comment by allangrds** [comment]
Isso já está sendo feito pelo @vcapretz?

**Comment by vcapretz** [comment]
Não @allangrds, pode pegar

**Comment by augusto-jm-amaral** [comment]
Transferido para https://github.com/pagarme/mercurio/issues/23.
